[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"
  ignore = "git log -1 --pretty=%B | grep -i '\\[deploy\\]' > /dev/null || exit 0 && exit 1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
