'use client'

import { useState, useEffect } from 'react'
import { Bell, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth } from '@/lib/auth-context'

const VAPID_PUBLIC_KEY = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY || ''

function urlBase64ToUint8Array(base64String: string) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4)
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/')
  const rawData = window.atob(base64)
  const outputArray = new Uint8Array(rawData.length)
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i)
  }
  return outputArray
}

export default function PushManager() {
  const { isAuthenticated } = useAuth()
  const [permission, setPermission] = useState<NotificationPermission>('default')
  const [subscribing, setSubscribing] = useState(false)
  const [supported, setSupported] = useState(true)

  useEffect(() => {
    if (typeof window === 'undefined') return
    const isSupported = 'serviceWorker' in navigator && 'PushManager' in window
    setSupported(isSupported)
    if (isSupported) {
      setPermission(Notification.permission)
    }
  }, [])

  const handleSubscribe = async () => {
    if (!supported) {
      toast.error('ఈ బ్రౌజర్‌లో పుష్ నోటిఫికేషన్లు సపోర్ట్ చేయవు.')
      return
    }

    setSubscribing(true)
    try {
      const result = await Notification.requestPermission()
      setPermission(result)

      if (result !== 'granted') {
        toast.warning('నోటిఫికేషన్ల పర్మిషన్ తిరస్కరించబడింది.')
        setSubscribing(false)
        return
      }

      const registration = await navigator.serviceWorker.ready
      
      if (!VAPID_PUBLIC_KEY) {
        throw new Error('VAPID public key is missing')
      }

      const subscribeOptions = {
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
      }

      const subscription = await registration.pushManager.subscribe(subscribeOptions)
      
      const rawSub = subscription.toJSON()
      if (!rawSub.endpoint || !rawSub.keys?.p256dh || !rawSub.keys?.auth) {
        throw new Error('Invalid subscription generated by browser')
      }

      const res = await fetch('/api/push/subscribe', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          endpoint: rawSub.endpoint,
          p256dh: rawSub.keys.p256dh,
          auth: rawSub.keys.auth,
        }),
      })

      if (res.ok) {
        toast.success('నోటిఫికేషన్లు విజయవంతంగా ఆన్ చేయబడ్డాయి! 🔔')
      } else {
        const errorData = await res.json()
        throw new Error(errorData.error || 'Failed to save subscription')
      }
    } catch (err: any) {
      console.error('Push subscription error:', err)
      toast.error(err.message || 'పుష్ నోటిఫికేషన్ల రిజిస్ట్రేషన్ విఫలమైంది.')
    } finally {
      setSubscribing(false)
    }
  }

  if (!supported) return null
  if (permission === 'granted') {
    return (
      <div className="bg-white rounded-2xl border border-gray-150 p-4 shadow-sm flex items-center gap-3 max-w-md mx-auto my-3">
        <div className="w-8 h-8 rounded-lg bg-green-50 text-green-600 flex items-center justify-center shrink-0">
          <Bell className="w-4 h-4" />
        </div>
        <p className="text-xs font-semibold text-gray-700">
          నోటిఫికేషన్లు ఆన్ చేయబడ్డాయి. మీరు అప్‌డేట్‌లను స్వీకరిస్తారు!
        </p>
      </div>
    )
  }

  return (
    <div className="bg-white rounded-2xl border border-gray-150 p-5 shadow-sm flex flex-col items-center text-center gap-4 max-w-md mx-auto my-4 relative overflow-hidden">
      <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0 animate-bounce">
        <Bell className="w-6 h-6" />
      </div>
      <div>
        <h3 className="text-base font-bold text-gray-900 mb-1">నోటిఫికేషన్లు పొందండి</h3>
        <p className="text-xs text-gray-500 font-medium max-w-xs leading-normal">
          తాజా స్థానిక వార్తలు, ప్రత్యేక ఆఫర్లు మరియు అప్‌డేట్‌లను నేరుగా మీ మొబైల్‌కు పొందడానికి నోటిఫికేషన్‌లను ఆన్ చేసుకోండి.
        </p>
      </div>

      <button
        onClick={handleSubscribe}
        disabled={subscribing}
        className="w-full bg-gradient-to-r from-blue-600 to-yellow-500 text-white font-bold py-3 px-6 rounded-xl hover:opacity-95 active:scale-[0.98] transition-all shadow-md flex items-center justify-center gap-2 text-sm disabled:opacity-70"
      >
        {subscribing ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin text-white" />
            ఆన్ చేస్తోంది...
          </>
        ) : (
          'నోటిఫికేషన్లు ఆన్ చేయండి'
        )}
      </button>
    </div>
  )
}
export { PushManager }
