-- Table: News
INSERT INTO public."News" ("id", "cityId", "title", "content", "imageUrl", "source", "isPublished", "createdAt") VALUES ('cmp8dtxc40026mavt8x0ttj9j', 'cmp8dtxb70000mavt7q4w47pi', 'Choutuppal Municipality Approves New Road Widening Project', 'The Choutuppal Municipality has approved a ₹15 crore road widening project for the Main Road stretch from Bus Stand to Highway Junction. The project is expected to be completed within 18 months and will ease traffic congestion in the town center. Local businesses have welcomed the move while requesting minimal disruption during construction.', NULL, 'Telangana Today', TRUE, '2026-05-16T13:28:49.157Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."News" ("id", "cityId", "title", "content", "imageUrl", "source", "isPublished", "createdAt") VALUES ('cmp8dtxc50028mavt2bdir5ab', 'cmp8dtxb70000mavt7q4w47pi', 'New Water Supply Scheme to Benefit 10,000 Households', 'The state government has sanctioned a new water supply scheme for Choutuppal under the Mission Bhagiratha program. The scheme will provide clean drinking water to over 10,000 households in the town and surrounding areas. Pipeline laying work has already begun and is expected to be completed by March next year.', 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800', 'Eenadu', TRUE, '2026-05-16T13:28:49.157Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."News" ("id", "cityId", "title", "content", "imageUrl", "source", "isPublished", "createdAt") VALUES ('cmp8dtxc6002amavtg0xak5yv', 'cmp8dtxb70000mavt7q4w47pi', 'Choutuppal RDO Office Inaugurates Digital Services Center', 'The RDO office in Choutuppal has inaugurated a new digital services center that will allow citizens to access various government services online. Services include land records, certificates, and pension applications. The center is equipped with 20 computers and trained staff to assist the public.', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800', 'Namaste Telangana', TRUE, '2026-05-16T13:28:49.158Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."News" ("id", "cityId", "title", "content", "imageUrl", "source", "isPublished", "createdAt") VALUES ('cmp8dtxc6002cmavtuydsu4tx', 'cmp8dtxb70000mavt7q4w47pi', 'Annual Choutuppal Jatara Festival Draws Record Crowds', 'The annual Choutuppal Jatara festival celebrated at the ancient Sri Rama Temple drew record crowds this year with over 50,000 devotees attending the three-day event. The festival featured cultural programs, traditional dances, and a grand procession. Local authorities made elaborate arrangements for crowd management and security.', 'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=800', 'Sakshi', TRUE, '2026-05-16T13:28:49.159Z'::timestamp) ON CONFLICT DO NOTHING;

-- Table: Blog
INSERT INTO public."Blog" ("id", "title", "slug", "coverImageUrl", "content", "authorId", "cityId", "isPublished", "createdAt", "updatedAt") VALUES ('cmp8dtxd1005emavtb3v00zhf', '5 Hidden Gems in Choutuppal You Must Visit', '5-hidden-gems-choutuppal', 'https://images.unsplash.com/photo-1587474260584-136574535ed5?w=800', '<h2>Discover Choutuppal</h2><p>Choutuppal is a town rich in culture and history. Here are 5 places you absolutely must visit...</p>', 'cmp8dtxba0004mavtyqcph9qw', 'cmp8dtxb70000mavt7q4w47pi', TRUE, '2026-05-16T13:28:49.190Z'::timestamp, '2026-05-16T13:28:49.190Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Blog" ("id", "title", "slug", "coverImageUrl", "content", "authorId", "cityId", "isPublished", "createdAt", "updatedAt") VALUES ('cmp8dtxd2005gmavtbxppffu1', 'How Digital Platforms Are Transforming Small Towns', 'digital-platforms-transforming-small-towns', 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800', '<h2>The Digital Revolution</h2><p>Small towns across India are embracing digital transformation at an unprecedented rate...</p>', 'cmp8dtxba0004mavtyqcph9qw', NULL, TRUE, '2026-05-16T13:28:49.190Z'::timestamp, '2026-05-16T13:28:49.190Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Blog" ("id", "title", "slug", "coverImageUrl", "content", "authorId", "cityId", "isPublished", "createdAt", "updatedAt") VALUES ('cmp8dtxd3005imavtj6t1xn01', 'Best Street Food in Telangana Towns', 'best-street-food-telangana', 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=800', '<h2>Street Food Paradise</h2><p>Telangana is famous for its incredible street food culture. From spicy mirchi bajji to sweet jalebi...</p>', 'cmp8dtxbc0006mavt3bpkbux9', 'cmp8dtxb70000mavt7q4w47pi', TRUE, '2026-05-16T13:28:49.191Z'::timestamp, '2026-05-16T13:28:49.191Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Blog" ("id", "title", "slug", "coverImageUrl", "content", "authorId", "cityId", "isPublished", "createdAt", "updatedAt") VALUES ('cmp8dtxdz007jmavtn7cklf9n', 'Why Every Local Business Needs a Digital Presence in 2025', 'local-business-digital-presence-2025', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800', '<h2>The Digital Revolution is Here</h2><p>In 2025, having a digital presence is no longer optional for local businesses. With over 80% of consumers searching online before making a purchase decision, businesses that are not visible online are losing customers every day.</p><h3>Key Benefits</h3><ul><li>Increased visibility in local search results</li><li>Building trust with customer reviews</li><li>Reaching younger demographics who primarily use mobile</li><li>Competing with larger chains on a level playing field</li></ul><p>The Choutuppal Super App makes it easy for local businesses to establish their digital presence without needing technical expertise. Simply list your business, add your services, and start receiving enquiries via WhatsApp!</p>', 'cmp8dtxba0004mavtyqcph9qw', 'cmp8dtxb70000mavt7q4w47pi', TRUE, '2026-05-16T13:28:49.224Z'::timestamp, '2026-05-16T13:28:49.224Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Blog" ("id", "title", "slug", "coverImageUrl", "content", "authorId", "cityId", "isPublished", "createdAt", "updatedAt") VALUES ('cmp8dtxe0007lmavtgvztf9aa', 'How Agents Are Earning ₹20,000+ Monthly with Choutuppal App', 'agent-earnings-guide-2025', 'https://images.unsplash.com/photo-1553729459-uj1ef3f78828?w=800', '<h2>The Agent Opportunity</h2><p>Choutuppal App agents are earning significant commissions by helping local businesses get online. Here is how the commission structure works and how you can maximize your earnings.</p><h3>Commission Structure</h3><ul><li><strong>Listings:</strong> 20% commission on every Pro (₹299) and Premium (₹499) listing you sell</li><li><strong>Banner Ads:</strong> 15% commission on monthly banner ad sales</li><li><strong>News Posts:</strong> 10% commission on sponsored news posts</li></ul><h3>Success Tips</h3><p>Top-performing agents focus on building relationships with business owners. Start with businesses you already know, show them the value of being listed, and the enquiries will speak for themselves.</p>', 'cmp8dtxba0004mavtyqcph9qw', NULL, TRUE, '2026-05-16T13:28:49.224Z'::timestamp, '2026-05-16T13:28:49.224Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Blog" ("id", "title", "slug", "coverImageUrl", "content", "authorId", "cityId", "isPublished", "createdAt", "updatedAt") VALUES ('cmp8dtxe1007nmavtbgv5cqwb', 'Own Your City: The Franchisee Opportunity', 'franchisee-opportunity-guide', 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800', '<h2>Become a City Admin</h2><p>The Choutuppal App franchisee model allows entrepreneurs to own and operate the platform in their city. As a City Admin, you get:</p><ul><li>Full management rights for your city</li><li>30% revenue share from all transactions in your city</li><li>Ability to recruit and manage agents</li><li>Complete content management for listings, news, and banners</li></ul><h3>Investment</h3><p>The one-time franchisee fee is ₹50,000. This gives you exclusive rights to operate in your city with full support from our platform team.</p>', 'cmp8dtxba0004mavtyqcph9qw', NULL, TRUE, '2026-05-16T13:28:49.225Z'::timestamp, '2026-05-16T13:28:49.225Z'::timestamp) ON CONFLICT DO NOTHING;

-- Table: AdminRequest
INSERT INTO public."AdminRequest" ("id", "userId", "cityName", "reason", "type", "status", "franchiseeFeePaid", "razorpayPaymentId", "agentCityId", "createdAt") VALUES ('cmp8dtxd1005cmavt9crtk33u', 'cmp8dtxbf000cmavt5aq9r3xj', 'Bhongir', 'I want to bring the Choutuppal App experience to Bhongir and manage local business listings.', 'city_admin', 'pending', FALSE, NULL, NULL, '2026-05-16T13:28:49.189Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."AdminRequest" ("id", "userId", "cityName", "reason", "type", "status", "franchiseeFeePaid", "razorpayPaymentId", "agentCityId", "createdAt") VALUES ('cmp8dtxdk006emavtrc65drhu', 'cmp8dtxbf000cmavt5aq9r3xj', 'Choutuppal', 'I want to help onboard businesses in my area', 'agent', 'pending', FALSE, NULL, 'cmp8dtxb70000mavt7q4w47pi', '2026-05-16T13:28:49.209Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."AdminRequest" ("id", "userId", "cityName", "reason", "type", "status", "franchiseeFeePaid", "razorpayPaymentId", "agentCityId", "createdAt") VALUES ('cmp8dtxdy007fmavtl5hbua8u', 'cmp8dtxbf000cmavt5aq9r3xj', 'Warangal', 'I want to bring the Choutuppal App model to Warangal. I have extensive local business contacts.', 'city_admin', 'pending', FALSE, NULL, NULL, '2026-05-16T13:28:49.223Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."AdminRequest" ("id", "userId", "cityName", "reason", "type", "status", "franchiseeFeePaid", "razorpayPaymentId", "agentCityId", "createdAt") VALUES ('cmp8dtxdz007hmavtnkuy5puk', 'cmp8dtxbf000cmavt5aq9r3xj', 'Choutuppal', 'I want to become an agent and help onboard businesses in my area.', 'agent', 'pending', FALSE, NULL, 'cmp8dtxb70000mavt7q4w47pi', '2026-05-16T13:28:49.223Z'::timestamp) ON CONFLICT DO NOTHING;

-- Table: Profile
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxek0092mavt9axttb5j', 'cmp8dtxba0004mavtyqcph9qw', 'Super Admin of Choutuppal App. Building the future of hyper-local services! 🚀', NULL, NULL, FALSE, NULL, TRUE, 1250, 45, '2026-05-16T13:28:49.244Z'::timestamp, '2026-05-16T13:28:49.244Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxek0094mavtprygbjt3', 'cmp8dtxbf000cmavt5aq9r3xj', 'Love exploring Choutuppal! Foodie 🍛 | Shopper 🛍️ | Local guide 📍', NULL, NULL, FALSE, NULL, FALSE, 85, 120, '2026-05-16T13:28:49.245Z'::timestamp, '2026-05-16T13:28:49.245Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxel0096mavtturffd71', 'cmp8dtxbc0006mavt3bpkbux9', 'Business owner in Choutuppal. Running Sri Venkateswara Tiffin Center since 2005! 🍽️', NULL, NULL, FALSE, NULL, FALSE, 210, 50, '2026-05-16T13:28:49.245Z'::timestamp, '2026-05-16T13:28:49.245Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxem0098mavt9lnxlb5c', 'cmp8dtxbd0008mavt96zjmdxl', 'Real estate & electronics entrepreneur. Serving Choutuppal with quality products! 🏠📱', NULL, NULL, FALSE, NULL, FALSE, 180, 65, '2026-05-16T13:28:49.246Z'::timestamp, '2026-05-16T13:28:49.246Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxem009amavtg5yp8z6w', 'cmp8dtxbe000amavtmxdzjyu5', 'Beauty expert & salon owner. Making Choutuppal beautiful one person at a time! 💇‍♀️✨', NULL, NULL, FALSE, NULL, FALSE, 350, 80, '2026-05-16T13:28:49.247Z'::timestamp, '2026-05-16T13:28:49.247Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxen009cmavtqv47jtfm', 'cmp8dtxbi000imavt8p9exy72', 'చౌటుప్పల్ నియోజకవర్గం ఎమ్మెలే. ప్రజల సేవలో ఎప్పుడూ! 🇮🇳 Serving the people of Choutuppal constituency.', NULL, NULL, TRUE, 'POLITICIAN', TRUE, 15000, 25, '2026-05-16T13:28:49.247Z'::timestamp, '2026-05-16T13:28:49.247Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxen009emavtok9gz7ab', 'cmp8dtxbj000kmavtk2a6wkka', 'చౌటుప్పల్ మున్సిపల్ చైర్మన్. పట్టణ అభివృద్ధి నా లక్ష్యం! 🏙️ Building a better Choutuppal.', NULL, NULL, TRUE, 'GOVT_OFFICIAL', TRUE, 8500, 30, '2026-05-16T13:28:49.248Z'::timestamp, '2026-05-16T13:28:49.248Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxeo009gmavt68aq32z0', 'cmp8dtxbk000mmavtg6adh05f', 'చౌటుప్పల్ కిరణ్ 📸 | Food blogger | Local events | తెలుగు content creator | Promoting local businesses 🤝', NULL, NULL, TRUE, 'INFLUENCER', TRUE, 5200, 450, '2026-05-16T13:28:49.248Z'::timestamp, '2026-05-16T13:28:49.248Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxeo009imavtkg4iqp0k', 'cmp8dtxbg000emavt8x32dre7', 'City Admin & Franchisee of Choutuppal App. Empowering local businesses! 💼', NULL, NULL, FALSE, NULL, FALSE, 500, 30, '2026-05-16T13:28:49.249Z'::timestamp, '2026-05-16T13:28:49.249Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Profile" ("id", "userId", "bio", "avatarUrl", "coverImageUrl", "isPublicFigure", "publicFigureCategory", "isVerified", "followersCount", "followingCount", "createdAt", "updatedAt") VALUES ('cmp8dtxep009kmavtjei35zpn', 'cmp8dtxbh000gmavtp7dqc3pm', 'Agent for Choutuppal. Helping businesses grow! 📈', NULL, NULL, FALSE, NULL, FALSE, 120, 200, '2026-05-16T13:28:49.249Z'::timestamp, '2026-05-16T13:28:49.249Z'::timestamp) ON CONFLICT DO NOTHING;

-- Table: Post
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxeq009mmavtdrwsucg2', 'cmp8dtxbi000imavt8p9exy72', 'చౌటుప్పల్ లో కొత్త రోడ్లు నిర్మాణం జరుగుతోంది... 🚧 మా ప్రభుత్వం ₹15 కోట్లు కేటాయించింది. త్వరలో ట్రాఫిక్ సమస్య తగ్గుతుంది! #ChoutuppalDevelopment #అభివృద్ధి', NULL, 342, 45, TRUE, FALSE, '2026-05-16T13:28:49.250Z'::timestamp, '2026-05-16T13:28:49.250Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxeq009omavtv2z1d6yx', 'cmp8dtxbi000imavt8p9exy72', 'నేడు చౌటుప్పల్ ప్రభుత్వ పాఠశాలలో డిజిటల్ క్లాస్‌రూమ్ ప్రారంభోత్సవం! 🏫💻 పిల్లల భవిష్యత్తు కోసం మేము కట్టుబడి ఉన్నాము. #Education #DigitalIndia', NULL, 228, 32, FALSE, FALSE, '2026-05-16T13:28:49.251Z'::timestamp, '2026-05-16T13:28:49.251Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxer009qmavt9l4rao4h', 'cmp8dtxbi000imavt8p9exy72', 'చౌటుప్పల్ జాతర ఈ ఏడాది ఘనంగా జరుగుతుంది! 🙏 అందరం కలిసి పాల్గొనండి. భక్తుల సౌకర్యార్థం ప్రత్యేక ఏర్పాట్లు చేశాము. 🪔', NULL, 456, 67, FALSE, FALSE, '2026-05-16T13:28:49.251Z'::timestamp, '2026-05-16T13:28:49.251Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxes009smavtbcdvhh7j', 'cmp8dtxbj000kmavtk2a6wkka', 'చౌటుప్పల్ మున్సిపాలిటీ నుండి మీ అందరికీ సందేశం! 🏙️ మంచినీటి సరఫరా పథకం పనులు వేగంగా జరుగుతున్నాయి. మార్చి నాటికి పూర్తవుతుంది! 💧 #MissionBhagiratha', NULL, 189, 23, TRUE, FALSE, '2026-05-16T13:28:49.252Z'::timestamp, '2026-05-16T13:28:49.252Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxes009umavtefpdi5pg', 'cmp8dtxbj000kmavtk2a6wkka', 'స్వచ్ఛ చౌటుప్పల్ - ఆదివారం శుభ్రత కార్యక్రమం! 🧹 అందరం పాల్గొనండి. మన పట్టణం మన బాధ్యత! #SwachhChoutuppal #CleanCity', NULL, 145, 18, FALSE, FALSE, '2026-05-16T13:28:49.253Z'::timestamp, '2026-05-16T13:28:49.253Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxet009wmavt4b1t2rc9', 'cmp8dtxbk000mmavtg6adh05f', 'చౌటుప్పల్ లో బెస్ట్ మసాలా దోశ! 🤤 శ్రీ వెంకటేశ్వర టిఫిన్ సెంటర్ లో ట్రై చేయండి రండి! నాకు ఇది ఎప్పటికీ ఫేవరెట్! ❤️ #ChoutuppalFood #LocalEats', '["https://images.unsplash.com/photo-1630383249896-424e482df921?w=600"]', 567, 89, FALSE, FALSE, '2026-05-16T13:28:49.253Z'::timestamp, '2026-05-16T13:28:49.253Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxeu009ymavtgj559tci', 'cmp8dtxbk000mmavtg6adh05f', 'చౌటుప్పల్ జాతర వైభవం! 🎊✨ ఈ ఏడాది రికార్డు స్థాయిలో భక్తులు వచ్చారు. సాంస్కృతిక కార్యక్రమాలు అద్భుతంగా ఉన్నాయి! 🪔🙏', '["https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=600"]', 834, 112, FALSE, FALSE, '2026-05-16T13:28:49.254Z'::timestamp, '2026-05-16T13:28:49.254Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxeu00a0mavtx0j2ijk3', 'cmp8dtxbf000cmavt5aq9r3xj', 'ఈ రోజు చౌటుప్పల్ మార్కెట్ లో కొనుగోలు! 🛍️ కూరగాయల ధరలు ఈ వారం చాలా బాగున్నాయి. టమాటా ₹20/kg, ఉల్లిపచ్చి ₹25/kg 🍅🧅', NULL, 45, 12, FALSE, FALSE, '2026-05-16T13:28:49.255Z'::timestamp, '2026-05-16T13:28:49.255Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxev00a2mavtzrnhsm7m', 'cmp8dtxbf000cmavt5aq9r3xj', 'Choutuppal App is so useful! Found the best salon in town through this app. Lakshmi Beauty Salon did an amazing job with my bridal makeup! 💄✨ Thank you @LakshmiDevi!', NULL, 67, 8, FALSE, FALSE, '2026-05-16T13:28:49.255Z'::timestamp, '2026-05-16T13:28:49.255Z'::timestamp) ON CONFLICT DO NOTHING;
INSERT INTO public."Post" ("id", "authorId", "content", "mediaUrls", "likesCount", "commentsCount", "isPinned", "isDeleted", "createdAt", "updatedAt") VALUES ('cmp8dtxew00a4mavtk5p58hrn', 'cmp8dtxbc0006mavt3bpkbux9', 'శ్రీ వెంకటేశ్వర టిఫిన్ సెంటర్ లో ఈ వారం ప్రత్యేకం! 🔥 పెసరట్టు + ఫిల్టర్ కాఫీ కాంబో ₹70 మాత్రమే! రండి ఆస్వాదించండి! ☕🥘', NULL, 89, 15, FALSE, FALSE, '2026-05-16T13:28:49.256Z'::timestamp, '2026-05-16T13:28:49.256Z'::timestamp) ON CONFLICT DO NOTHING;
